<a href="https://colab.research.google.com/github/Vaibhavsj75/Diamond-Problem-/blob/main/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NAME: Vaibhav Jadhav
ROLL_NO: 13211
BATCH: B1

In [ ]:
import pandas as pd

In [3]:
import pandas as pd
df = pd.read_excel("/content/Players.xlsx")

In [4]:
df.head(5)

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    566 non-null    object
 1   DOB            471 non-null    datetime64[ns]
 2   Batting_Hand   563 non-null    object
 3   Bowling_Skill  502 non-null    object
 4   Country        471 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 22.2+ KB

In [6]:
df.describe()

                                 DOB
count                            471
mean   1984-11-15 10:48:09.171974528
min              1969-06-30 00:00:00
25%              1981-05-21 00:00:00
50%              1985-01-25 00:00:00
75%              1989-02-14 12:00:00
max              1998-07-18 00:00:00

In [7]:
df.index

RangeIndex(start=0, stop=566, step=1)

In [8]:
df.shape

(566, 5)

In [9]:
df.columns.names

FrozenList([None])

In [10]:
df.columns.values

array(['Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill', 'Country'],
      dtype=object)

In [11]:
df.dtypes

Player_Name              object
DOB              datetime64[ns]
Batting_Hand             object
Bowling_Skill            object
Country                  object
dtype: object

In [12]:
df.shape

(566, 5)

In [13]:
df.columns

Index(['Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill', 'Country'], dtype='object')

In [14]:
df.iloc[200]

Player_Name                   J Suchith
DOB                 1994-01-16 00:00:00
Batting_Hand                  Left_Hand
Bowling_Skill    Slow left-arm orthodox
Country                           India
Name: 200, dtype: object

In [16]:
df.iloc[:,2:7]

    Batting_Hand           Bowling_Skill   Country
0     Right_Hand        Right-arm medium     India
1     Right_Hand      Right-arm offbreak     India
2     Right_Hand      Right-arm offbreak     India
3     Right_hand    Left-arm fast-medium       NaN
4     Right_Hand      Right-arm offbreak       NaN
..           ...                     ...       ...
561   Right_Hand        Right-arm medium  Pakistan
562   Right_Hand         Legbreak googly     India
563    Left_Hand  Slow left-arm orthodox     India
564   Right_Hand                     NaN     India
565   Right_Hand    Left-arm fast-medium     India

[566 rows x 3 columns]

In [17]:
df.iloc[:101,1:6]

           DOB Batting_Hand           Bowling_Skill       Country
0   1991-02-24   Right_Hand        Right-arm medium         India
1   1983-12-05   Right_Hand      Right-arm offbreak         India
2   1977-09-19   Right_Hand      Right-arm offbreak         India
3          NaT   Right_hand    Left-arm fast-medium           NaN
4          NaT   Right_Hand      Right-arm offbreak           NaN
..         ...          ...                     ...           ...
96  1982-10-15   Right_Hand                     NaN         India
97  1987-03-11    Left_Hand   Right-arm medium-fast   New Zealand
98  1979-03-29   Right_Hand                Legbreak         India
99  1985-07-03    Left_Hand                Legbreak  South Africa
100 1990-04-10   Right_Hand  Slow left-arm orthodox     Australia

[101 rows x 4 columns]

In [18]:
df.iloc[:5,4:6]

  Country
0   India
1   India
2   India
3     NaN
4     NaN